CREATE TABLE accounts (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(50) NOT NULL,
	password VARCHAR(255) NOT NULL,
	CONSTRAINT usernameUnique UNIQUE (username)

);

CREATE TABLE posts (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(50) NOT NULL, 
	body VARCHAR(255) NOT NULL, 
	accountId INT UNSIGNED NOT NULL,
	FOREIGN KEY(accountId) REFERENCES accounts(id)
);


CREATE TABLE comments (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	comment VARCHAR(255) NOT NULL,
	postid INT UNSIGNED NOT NULL,
	accountId INT UNSIGNED NOT NULL,
	FOREIGN KEY (postid) REFERENCES posts(id) ON DELETE CASCADE,
	FOREIGN KEY (accountId) REFERENCES accounts(id)
);
